### ISSUE TITLE
Non-standard resolution support

### ISSUE THREAD

**Issue by Morisabeau** [AvroraPolnareff/warframe-color-picker#11]
https://cdn.discordapp.com/attachments/268880151012442115/790559407389933598/unknown.png

**Comment by AvroraPolnareff** [comment]
I think the example above is ok. People rarely use such high resolutions without scaling or opening the browser in full screen.

**Comment by Morisabeau** [comment]
> I think the example above is ok. People rarely use such high resolutions without scaling or opening the browser in full screen.

The issue is, whenever you scale up the page, this weirdness occurs:
![image](https://user-images.githubusercontent.com/74872505/104332057-d6616480-5500-11eb-9e68-2ae237b0d0b2.png)
