### ISSUE TITLE
Share with URL

### ISSUE THREAD

**Issue by CKylinMC** [AvroraPolnareff/warframe-color-picker#13]
Could you add a way to share with a single URL?
I mean when I click "export" then put all my color data in one URL, I just need to send it to my friend, and my friend just click it and will open the page that will restore all my color data automatically. That will be much easier to share than the current way.
Thanks :D

**Comment by Morisabeau** [comment]
> I mean when I click "export" then put all my color data in one URL, I just need to send it to my friend, and my friend just click it and will open the page that will restore all my color data automatically. That will be much easier to share than the current way.

Oh hey! Thanks for the feedback. That'd actually make a good addition, as we'll get rid of an element that could've been avoided from the start to make the whole thing more fluid, predictable and easy to understand. I'll add it to our design project and tell my friend about it.

There are other updates and changes that are currently on the way, so I've got no idea how soon we'll be set and ready to roll it all out. So, in other words, ETA: hopefully as soon as possible. :)
