### ISSUE TITLE
Rename "suggestions.svg" for Windows environments

### ISSUE THREAD

**Issue by CKylinMC** [AvroraPolnareff/warframe-color-picker#18]
![image](https://user-images.githubusercontent.com/11648014/122554025-02ae7d80-d06b-11eb-8b99-746d4de82427.png)

These two svg files have the same name (only case differences) which is not friendly for Windows environments.

I opened these files and found SUGGESTIONS.svg is one time larger than suggestions.svg, so maybe it should be renamed something like "suggestions@2x.svg" is better?

**Comment by AvroraPolnareff** [comment]
Hi! I've removed suggestions.svg file

**Comment by CKylinMC** [comment]
Thanks!
