### ISSUE TITLE
Let "SELECTED COLOR" clickable

### ISSUE THREAD

**Issue by CKylinMC** [AvroraPolnareff/warframe-color-picker#19]
I think let colors in "SELECTED COLOR" panel be clickable, when click a color in that panel then switch current color to the clicked one is more friendly to use and understand.

![image](https://user-images.githubusercontent.com/11648014/122558698-f62d2380-d070-11eb-9f74-6acf56f21ab7.png)

**Comment by AvroraPolnareff** [comment]
Hi! It would be nice feature. If you want, feel free to contribute, just let me know.

**Comment by CKylinMC** [comment]
#20 I opened a pr

**Comment by CKylinMC** [comment]
PR has been merged, so I'll close this.
